- name: Install git
  apt: name=git state=latest

- name: Install htop
  apt: name=htop state=latest

- name: Install exuberant-ctags
  apt: name=exuberant-ctags state=latest

- name: Install vim
  apt: name=vim state=latest

- name: Install zsh
  apt: name=zsh state=latest

- name: Install sudo
  apt: name=sudo state=latest

- name: Create the sudo group
  group:
    name=sudo
    state=present

- name: Create a new user
  user:
    name=tyler
    state=present
    groups="sudo"
    shell=/bin/zsh
    password=$6$rounds=100000$kOPsL36LobJSBkbM$qs04KIxy/i7hxwrNnaQhz8vVF7lt1UOqydXYKIjwJ./u0diaSvdREIVrs.wmduWHCu4IOfll66d8Q.HQ2RWdC/

- name: Create home directories
  file: path=/home/tyler/{{ item }}
    state=directory
    owner=tyler
    group=tyler
    mode=0700
  with_items:
    - src
    - backups
    - bin
    - projects
    - scripts
    - tmp

- name: Check out the environment repo.
  git:
    repo=https://github.com/roberttstephens/environment.git
    dest=/home/tyler/src/environment
    update=yes

- name: Set symbolic links
  file:
    src=/home/tyler/src/environment/{{ item.src }}
    dest=/home/tyler/{{ item.dest }}
    state=link
    owner=tyler
    group=tyler
  with_items:
    - { src: '_aliases', dest: '.aliases'}
    - { src: '_gitconfig', dest: '.gitconfig'}
    - { src: '_gitignore', dest: '.gitignore'}
    - { src: '_gvimrc', dest: '.gvimrc'}
    - { src: '_vim', dest: '.vim'}
    - { src: '_vimrc', dest: '.vimrc'}
    - { src: '_shrc', dest: '.shrc'}
    - { src: 'shared_bin', dest: 'shared_bin'}


- name: Source shared shrc file.
  lineinfile:
    dest=/home/tyler/{{ item }}
    line="if [ -f ~/.shrc ]; then source ~/.shrc; fi"
  with_items:
    - .bashrc
    - .zshrc
